version: "3.9"

services:
  mcp-proalpha:
    build: .
    container_name: mcp-proalpha
    env_file:
      - .env
    ports:
      - "${MCP_PORT:-8000}:${MCP_PORT:-8000}"
      - "${API_SERVER_PORT:-8081}:${API_SERVER_PORT:-8081}"
    volumes:
      - ./:/app
    command: python -m app
